name: multimodal-rag
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core dependencies managed by Conda
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Make sure your NVIDIA driver is compatible
  - ffmpeg
  - pip

  # Python packages installed via Pip
  - pip:
    - transformers==4.37.2
    - bitsandbytes==0.41.3
    - accelerate==0.25.0
    - git+https://github.com/openai/whisper.git
    - gradio
    - gTTS
    - nltk
    - Pillow
    - numpy
    - requests